import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from '@/layouts/Header'
import Sidebar from '@/layouts/Siderbar'
import { Providers } from './providers'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Header />  
          <Header />
          <Sidebar />
            <div className='app'>
              {children}
            </div>
        </Providers>
      </body>
    </html>
  )
}
    